# TODO docker build env, maybe further.. azure???
sudo: false

language:
  - cpp

matrix:
  incldue:
    - name: Test Ubuntu 16.04 + gcc-7
    os: linux
    dist: xenial
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        package:
          - g++-7
    compiler: gcc
    env:
      - BUILD_TYPE=Debug
    script:
      - sh Scripts/travis_build_default.sh
    - name: Test Ubuntu 16.04 + gcc-5
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            -ubuntu-toolchain-r-test
          package:
            - g++-5
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

before_install:
  - pip install --user cpp-coveralls

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: jaeho9929@gmail.com