# TODO docker build env, maybe further.. azure???
sudo: false

language:
  - cpp

matrix:
  include:
  - name: "Test Ubuntu 16.04(xenial) + gcc-7"
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    script:
      - sh Scripts/travis_build_default.sh

  - name: "Test Ubuntu 16.04(xenial) + gcc-6"
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
    script:
      - sh Scripts/travis_build_default.sh

before_install:
  - pip install --user cpp-coveralls

#script:
#  - sh Scripts/travis_build_default.sh

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*google.*"
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash < (curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

notifications:
  email: 
    recipients:
    - jaeho9929@gmail.com
    on_success: change  # default: change
    on_failure: always  # default: always