# TODO docker build env, maybe further.. azure???
sudo: false

language:
  - cpp

matrix:
  include:
  - name: "Ubuntu 16.04 + gcc-7"
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    script:
      - sh Scripts/travis_build_default.sh

  - name: "Ubuntu 16.04 + gcc-6"
    os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
    script:
      - sh Scripts/travis_build_default.sh

before_install:
  - pip install --user cpp-coveralls

#script:
#  - sh Scripts/travis_build_default.sh

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*google.*"

notifications:
  email: 
    recipients:
    - jaeho9929@gmail.com
    on_success: change  # default: change
    on_failure: always  # default: always