codecov:
  notify:
    require_ci_to_pass : yes

coverage:
  precision: 2
  round: down
  range: 50...80

  status:
    project: true
    patch: true
    changes: true

  ignore:
    - 'build'
    - 'cmake'
    - 'libs'
    - 'Scripts'
    - 'test'

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default